
--drop table T_CORRUPTEDFILES;
CREATE table T_CORRUPTEDFILES 
(
TDAY Date DEFAULT to_date('2011/01/01 12:00:00am', 'yyyy/mm/dd hh:mi:ssam') NOT NULL, 
SITENAME VARCHAR2(128) DEFAULT 'unknown' NOT NULL,
SUMFLAG NUMBER(38,0) DEFAULT 0 NOT NULL, 
NACC NUMBER(38,0) DEFAULT 0 NOT NULL,  
FILENAME VARCHAR2(400 BYTE) DEFAULT 'unknown' NOT NULL,
JobExitCode NUMBER(38,0) DEFAULT 0 NOT NULL, 
CONSTRAINT "T_CORRUPTEDFILES_UC_A" UNIQUE (TDAY, SITENAME, JobExitCode, FILENAME)
);

--drop index  IN_T_CORRUPTEDFILES_A;
create index IN_T_CORRUPTEDFILES_A on T_CORRUPTEDFILES ( TDAY );

