"""
@author: Pedro Salgado
@contact: pedro.salgado@cern.ch
@since: 0.3
@version: $Id: data.py,v 1.7 2010-10-12 08:07:10 vgaronne Exp $
"""


dates = [
    '2007-01-01 00:00:00',
    '2007-1-01 00:00:00',
    '2007-01-1 00:00:00',
    '2007-01-01 0:00:00',
    '2007-01-01 00:0:00',
    '2007-01-01 00:00:0',
    '2007-1-1 0:0:0',
    '2007-12-31 23:59:59',
    '2007-1-1',
    '2007-01-01'
]

dates_invalid = [
    '2007-01-01 00:00:60',
    '2007-01-01 00:60:00',
    '2007-01-01 24:00:00',
    '2007-02-30 00:00:00'
]

owners = [
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=DPS/CN=Alex Villazon',
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=DPS/CN=Martin Rabanser',
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=Experimental Physics/OU=HEPHY/CN=Brigitte Epp',
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=Experimental Physics/OU=HEPHY/CN=Harald Duer',
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=Experimental Physics/OU=HEPHY/CN=Peter Oettl',
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=ZID/CN=Markus Brejla',
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=astro/CN=Patrick Jussel',
    '/C=AT/O=AustrianGrid/OU=UIBK/OU=astro/CN=Wolfgang Kausch',
    '/C=AU/O=APACGrid/OU=The University of Melbourne/CN=Glenn R. Moloney',
    '/C=AU/O=APACGrid/OU=USYD/CN=Aldo F. Saavedra',
    '/C=AU/O=APACGrid/OU=USYD/CN=Jason Lee',
    '/C=CA/O=Grid/OU=lps.umontreal.ca/CN=Pierre Antoine',
    '/C=CA/O=Grid/OU=lps.umontreal.ca/CN=Rashid Mehdiyev',
    '/C=CA/O=Grid/OU=phys.ualberta.ca/CN=Bryan L Caron',
    '/C=CA/O=Grid/OU=phys.ualberta.ca/CN=Jiansen Lu',
    '/C=CA/O=Grid/OU=phys.uvic.ca/CN=Tayfun Ince',
    '/C=CA/O=Grid/OU=westgrid.ca/CN=Erfan Rezaie_64/Email=erezaie@sfu.ca',
    '/C=CA/O=Grid/OU=westgrid.ca/CN=Isabel Trigger_95/Email=itrigger@triumf.ca',
    '/C=CA/O=Grid/OU=westgrid.ca/CN=Rodney Walker',
    '/C=CH/O=CERN/OU=GRID/CN=Andreas Wildauer 0230',
    '/C=CH/O=CERN/OU=GRID/CN=Andrew Hamilton 9405',
    '/C=CH/O=CERN/OU=GRID/CN=Attila Krasznahorkay 8579',
    '/C=CH/O=CERN/OU=GRID/CN=Benjamin Gaidioz 2383',
    '/C=CH/O=CERN/OU=GRID/CN=Chaouki Boulahouache 2341',
    '/C=CH/O=CERN/OU=GRID/CN=David Cameron 0841',
    '/C=CH/O=CERN/OU=GRID/CN=Dietrich Liko 7572',
    '/C=CH/O=CERN/OU=GRID/CN=Eric Jansen 4902',
    '/C=CH/O=CERN/OU=GRID/CN=Feng Cunfeng',
    '/C=CH/O=CERN/OU=GRID/CN=Frederik Orellana 5894 - ATLAS',
    '/C=CH/O=CERN/OU=GRID/CN=Junichi Tanaka 9382',
    '/C=CH/O=CERN/OU=GRID/CN=Martin Flechl 5835',
    '/C=CH/O=CERN/OU=GRID/CN=Michael Leyton 4140',
    '/C=CH/O=CERN/OU=GRID/CN=Miguel De Oliveira Branco 2423',
    '/C=CH/O=CERN/OU=GRID/CN=Nathan Triplett 3729',
    '/C=CH/O=CERN/OU=GRID/CN=Osamu Jinnouchi 3698',
    '/C=CH/O=CERN/OU=GRID/CN=Pedro Emanuel De Castro Faria Salgado 1589',
    '/C=CH/O=CERN/OU=GRID/CN=Ricardo Brito Da Rocha 1186',
    '/C=CH/O=CERN/OU=GRID/CN=Richard Hawkings 3170',
    '/C=CH/O=CERN/OU=GRID/CN=Simone Campana 7461 - ATLAS',
    '/C=CH/O=CERN/OU=GRID/CN=Soshi Tsuno 9389',
    '/C=CH/O=CERN/OU=GRID/CN=Till Felix Eifert 1589',
    '/C=CN/O=HEP/O=IHEP/OU=PHYS/CN=Lian-You SHAN',
    '/C=CN/O=HEP/O=SDU/OU=PHYS/CN=Liu Dong/serialNumber=145',
    '/C=CN/O=HEP/OU=IHEP/CN=wanglu',
    '/C=DE/O=GermanGrid/OU=Universitaet Siegen/CN=Wolfgang Walkowiak',
    '/C=ES/O=DATAGRID-ES/O=IFIC/CN=Farida Fassi',
    '/C=ES/O=DATAGRID-ES/O=IFIC/CN=Luis March Ruiz',
    '/C=ES/O=DATAGRID-ES/O=IFIC/CN=Santiago Gonzalez de la Hoz',
    '/C=ES/O=DATAGRID-ES/O=PIC/CN=Xavier Espinal Curull',
    '/C=FR/O=CNRS/CN=GRID-FR',
    '/C=GR/O=HellasGrid/OU=grid.auth.gr/CN=Christos Anastopoulos',
    '/C=GR/O=HellasGrid/OU=ntua.gr/CN=Mike S. Bachtis',
    '/C=IL/O=IUCC/OU=Weizmann/CN=Ohad Silbert',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Bologna/CN=Davide Caforio',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Bologna/CN=Lorenzo Bellagamba',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Genova/CN=Andrea Coccaro',
    '/C=IT/O=INFN/OU=Personal Certificate/L=LNF/CN=Elisabetta Vilucchi',
    '/C=IT/O=INFN/OU=Personal Certificate/L=LNF/CN=Maria Lorenza Ferrer/emailAddress=Maria.Lorenza.Ferrer@lnf.infn.it',
    '/C=IT/O=INFN/OU=Personal Certificate/L=LNF/CN=Wen Mei/emailAddress=meiwen@lnf.infn.it',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Lecce/CN=Andrea Ventura',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Milano/CN=Guido Negri 2',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Milano/CN=Leonardo Carminati',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Milano/CN=Marcello Fanti',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Milano/CN=Silvia Resconi/emailAddress=Silvia.Resconi@mi.infn.it',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Milano/CN=Simone Montesano',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Milano/CN=Tommaso Lari',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Milano/CN=Umberto De Sanctis',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Napoli/CN=Michela Biglietti',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Napoli/CN=elisa musto',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Napoli/CN=francesco conventi',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Napoli/CN=gianpaolo carlino',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Pavia/CN=Daniela Rebuzzi',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Pavia/CN=Diana Scannicchio/emailAddress=Diana.Scannicchio@pv.infn.it',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Pisa/CN=Iacopo Vivarelli',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Pisa/CN=Paolo Francavilla',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Pisa/CN=francesca sarri',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Roma 1/CN=Alessandro De Salvo/emailAddress=Alessandro.DeSalvo@roma1.infn.it',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Roma 1/CN=Alessandro Di Girolamo',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Roma 1/CN=Antonio Sidoti',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Roma 1/CN=Ekaterina Kuznetsova',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Roma 3/CN=Addolorata Farilla',
    '/C=IT/O=INFN/OU=Personal Certificate/L=Roma 3/CN=Sara Diglio',
    '/C=JP/O=KEK/OU=CRC/OU=OUHEPL/CN=Daisuke Naito',
    '/C=PL/O=GRID/O=IFJ/CN=Anna Kaczmarska - Atlas',
    '/C=PL/O=GRID/O=INP/CN=Andrzej Olszewski',
    '/C=PL/O=GRID/O=INP/CN=Tadeusz Szymocha/Email=Tadeusz.Szymocha@ifj.edu.pl',
    '/C=PT/O=LIPCA/O=LIP/OU=Coimbra/CN=Filipe Veloso',
    '/C=PT/O=LIPCA/O=LIP/OU=Coimbra/CN=Nuno Castro',
    '/C=RU/O=RDIG/OU=users/OU=jinr.ru/CN=Arshak Tonoyan',
    '/C=RU/O=RDIG/OU=users/OU=jinr.ru/CN=Mariya Shiyakova',
    '/C=SI/O=SiGNET/O=IJS/OU=F9/CN=Borut Kersevan',
    '/C=SI/O=SiGNET/O=IJS/OU=F9/CN=Borut Kersevan/serialNumber=13',
    '/C=TW/O=AS/OU=PHYS/CN=Jiawei Zhao/emailAddress=Jiawei.Zhao@cern.ch',
    '/C=TW/O=AS/OU=PHYS/CN=suijian zhou/emailAddress=suijian.zhou@cern.ch',
    '/C=TW/O=AS/OU=PHYS/CN=zhijun liang/emailAddress=zhijun.liang@cern.ch',
    '/C=UK/O=eScience/OU=Birmingham/L=ParticlePhysics/CN=chun lik tan',
    '/C=UK/O=eScience/OU=Birmingham/L=ParticlePhysics/CN=dimitrios typaldos',
    '/C=UK/O=eScience/OU=Birmingham/L=ParticlePhysics/CN=joseph lilley',
    '/C=UK/O=eScience/OU=Birmingham/L=ParticlePhysics/CN=peter watkins',
    '/C=UK/O=eScience/OU=Birmingham/L=ParticlePhysics/CN=richard booth',
    '/C=UK/O=eScience/OU=CLRC/L=RAL/CN=julie kirk',
    '/C=UK/O=eScience/OU=Cambridge/L=UCS/CN=frederic brochu',
    '/C=UK/O=eScience/OU=Cambridge/L=UCS/CN=karl harrison',
    '/C=UK/O=eScience/OU=Cambridge/L=UCS/CN=karl harrison002',
    '/C=UK/O=eScience/OU=Cambridge/L=UCS/CN=thomas barber',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=alexander cheplakov',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=caitriana nicholson',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=catherine wright',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=daniel clements',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=michael kenyon',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=richard st denis',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=sarah allwood',
    '/C=UK/O=eScience/OU=Glasgow/L=Compserv/CN=thomas doherty',
    '/C=UK/O=eScience/OU=Lancaster/L=Physics/CN=alastair dewhurst',
    '/C=UK/O=eScience/OU=Lancaster/L=Physics/CN=darren price',
    '/C=UK/O=eScience/OU=Lancaster/L=Physics/CN=james catmore',
    '/C=UK/O=eScience/OU=Lancaster/L=Physics/CN=lee de mora',
    '/C=UK/O=eScience/OU=Lancaster/L=Physics/CN=susan cheatham',
    '/C=UK/O=eScience/OU=Liverpool/L=CSD/CN=helen hayward',
    '/C=UK/O=eScience/OU=Liverpool/L=CSD/CN=paul prichard',
    '/C=UK/O=eScience/OU=Manchester/L=HEP/CN=carl gwilliam',
    '/C=UK/O=eScience/OU=Manchester/L=HEP/CN=paul miyagawa',
    '/C=UK/O=eScience/OU=Oxford/L=OeSC/CN=elizabeth gallas',
    '/C=UK/O=eScience/OU=Oxford/L=OeSC/CN=florian heinemann',
    '/C=UK/O=eScience/OU=Oxford/L=OeSC/CN=kristin lohwasser',
    '/C=UK/O=eScience/OU=Oxford/L=OeSC/CN=maria fiascaris',
    '/C=UK/O=eScience/OU=Oxford/L=OeSC/CN=oleg brandt',
    '/C=UK/O=eScience/OU=QueenMaryLondon/L=Physics/CN=akira shibata',
    '/C=UK/O=eScience/OU=QueenMaryLondon/L=Physics/CN=kondo gnanvo',
    '/C=UK/O=eScience/OU=RoyalHollowayLondon/L=Physics/CN=christina potter',
    '/C=UK/O=eScience/OU=RoyalHollowayLondon/L=Physics/CN=ricardo goncalo',
    '/C=UK/O=eScience/OU=RoyalHollowayLondon/L=Physics/CN=tracey berry',
    '/C=UK/O=eScience/OU=Sheffield/L=CICS/CN=davide costanzo',
    '/C=UK/O=eScience/OU=UCL/L=EISD/CN=alan barr',
    '/C=UK/O=eScience/OU=UCL/L=EISD/CN=lily asquith',
    '/DC=ORG/DC=SEE-GRID/O=People/O=Institute of Physics Belgrade/CN=Nenad Vranjes',
    '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=dcameron',
    '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mlassnig',
    '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=vgaronne'
    '/DC=cz/DC=cesnet-ca/O=Institute of Physics of the Academy of Sciences of the CR/CN=Jiri Chudoba',
    '/DC=cz/DC=cesnet-ca/O=Institute of Physics of the Academy of Sciences of the CR/CN=Miroslav Jahoda',
    '/DC=es/DC=irisgrid/O=ifae/CN=jordi-nadal',
    '/DC=org/DC=doegrids/OU=People/CN=Adam Cunha 170349',
    '/DC=org/DC=doegrids/OU=People/CN=Alex Harvey 408174',
    '/DC=org/DC=doegrids/OU=People/CN=Alexandre Vaniachine 107991',
    '/DC=org/DC=doegrids/OU=People/CN=Alexei Klimentov 739513',
    '/DC=org/DC=doegrids/OU=People/CN=Alexei Klimentov 849938',
    '/DC=org/DC=doegrids/OU=People/CN=Arnab K. Pal 250010',
    '/DC=org/DC=doegrids/OU=People/CN=Arthur Marques Moraes',
    '/DC=org/DC=doegrids/OU=People/CN=Arthur Marques Moraes 805011',
    '/DC=org/DC=doegrids/OU=People/CN=Ayana Tamu Holloway 684910',
    '/DC=org/DC=doegrids/OU=People/CN=David Adams 407137',
    '/DC=org/DC=doegrids/OU=People/CN=David Strom 557592',
    '/DC=org/DC=doegrids/OU=People/CN=Douglas Benjamin 438916',
    '/DC=org/DC=doegrids/OU=People/CN=Eric Feng 748752',
    '/DC=org/DC=doegrids/OU=People/CN=Erik M Brubake',
    '/DC=org/DC=doegrids/OU=People/CN=George Redlinger 319908',
    '/DC=org/DC=doegrids/OU=People/CN=Gustaaf Brooijmans 815052',
    '/DC=org/DC=doegrids/OU=People/CN=Halasya-Siva Subramania 145204',
    '/DC=org/DC=doegrids/OU=People/CN=Hong Ma 981697',
    '/DC=org/DC=doegrids/OU=People/CN=Horst Severini 926890',
    '/DC=org/DC=doegrids/OU=People/CN=Ivan Logashenko 996988',
    '/DC=org/DC=doegrids/OU=People/CN=Jack Cranshaw 899901',
    '/DC=org/DC=doegrids/OU=People/CN=James Proudfoot 340219',
    '/DC=org/DC=doegrids/OU=People/CN=Jeremy Love 241692',
    '/DC=org/DC=doegrids/OU=People/CN=Jerry Gieraltowski 633663',
    '/DC=org/DC=doegrids/OU=People/CN=John Butler 962243',
    '/DC=org/DC=doegrids/OU=People/CN=Karthik Arunachalam 265532',
    '/DC=org/DC=doegrids/OU=People/CN=Ketevi A. Assamagan 890385',
    '/DC=org/DC=doegrids/OU=People/CN=Kevin Black 30752',
    '/DC=org/DC=doegrids/OU=People/CN=Kyle Cranmer 694748',
    '/DC=org/DC=doegrids/OU=People/CN=LEUNG FOOK CHEONG Annabelle 571152',
    '/DC=org/DC=doegrids/OU=People/CN=Marco Mambelli 325802',
    '/DC=org/DC=doegrids/OU=People/CN=Mark Sosebee 270653',
    '/DC=org/DC=doegrids/OU=People/CN=Moustapha Thioye 22195',
    '/DC=org/DC=doegrids/OU=People/CN=Muhammad Saleem 596127',
    '/DC=org/DC=doegrids/OU=People/CN=Neng Xu 861919',
    '/DC=org/DC=doegrids/OU=People/CN=Nurcan Ozturk 155817',
    '/DC=org/DC=doegrids/OU=People/CN=Nurcan Ozturk 18551',
    '/DC=org/DC=doegrids/OU=People/CN=Olga Igonkina 547330',
    '/DC=org/DC=doegrids/OU=People/CN=Oliver Keith Baker 129066',
    '/DC=org/DC=doegrids/OU=People/CN=Oliver Keith Baker 843758',
    '/DC=org/DC=doegrids/OU=People/CN=Paul Nilsson 536150',
    '/DC=org/DC=doegrids/OU=People/CN=Pavel Nevski 983037',
    '/DC=org/DC=doegrids/OU=People/CN=Sanjay Padhi 496075',
    '/DC=org/DC=doegrids/OU=People/CN=Sarah Marie Demers 317080',
    '/DC=org/DC=doegrids/OU=People/CN=Seth Caughron 569303',
    '/DC=org/DC=doegrids/OU=People/CN=Seth Zenz 97524',
    '/DC=org/DC=doegrids/OU=People/CN=Stephane Willocq 605034',
    '/DC=org/DC=doegrids/OU=People/CN=Stephen J. Gowdy 119167',
    '/DC=org/DC=doegrids/OU=People/CN=Tadashi Maeno',
    '/DC=org/DC=doegrids/OU=People/CN=Tadashi Maeno 199576',
    '/DC=org/DC=doegrids/OU=People/CN=Torre Wenaus 415962',
    '/DC=org/DC=doegrids/OU=People/CN=Vikas Bansal 74920',
    '/DC=org/DC=doegrids/OU=People/CN=Wensheng Deng 90806',
    '/DC=org/DC=doegrids/OU=People/CN=tetteh addy 794395',
    '/O=GRID-FR/C=CH/O=UNIBE/OU=LHEP/CN=Cyril Topfel',
    '/O=GRID-FR/C=CN/O=NJU/OU=PD/CN=Jialun Ping/emailAddress=jlping@njnu.edu.cn/CN=proxy',
    '/O=GRID-FR/C=FR/O=CEA/OU=DAPNIA/CN=Jerome Schwindling',
    '/O=GRID-FR/C=FR/O=CNRS/OU=CPPM/CN=Bernardo Resende',
    '/O=GRID-FR/C=FR/O=CNRS/OU=CPPM/CN=Jean-Baptiste De vivie de regie',
    '/O=GRID-FR/C=FR/O=CNRS/OU=CPPM/CN=Karim Bernardet',
    '/O=GRID-FR/C=FR/O=CNRS/OU=CPPM/CN=Lorenzo Feligioni',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LAL/CN=Claire Adam-Bourdarios',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LAL/CN=Emmanuel Turlay',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LAL/CN=Laurent Duflot',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LAPP/CN=Nicolas Kerschen',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LAPP/CN=Stephane Jezequel',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LPNHE/CN=Frederic Derue',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LPNHE/CN=Melissa Ridel',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LPNHE/CN=Pietro Cavalleri',
    '/O=GRID-FR/C=FR/O=CNRS/OU=LPSC/CN=Julien Morel',
    '/O=GRID-FR/C=FR/O=CNRS/OU=Lpsc/CN=Arnaud Lucotte',
    '/O=GRID-FR/C=JP/O=UT/OU=ICEPP/CN=Junichi Tanaka',
    '/O=GRID-FR/C=RO/O=UPB/OU=CSE/CN=Adrian Muraru',
    '/O=GermanGrid/OU=DESY/CN=Andreas Haupt',
    '/O=GermanGrid/OU=DESY/CN=Aura Rosca',
    '/O=GermanGrid/OU=DESY/CN=Judita Mamuzic',
    '/O=GermanGrid/OU=DESY/CN=Kai Leffhalm',
    '/O=GermanGrid/OU=DESY/CN=Martin zur Nedden',
    '/O=GermanGrid/OU=DESY/CN=Michael Volkmann',
    '/O=GermanGrid/OU=DESY/CN=Regina Kwee',
    '/O=GermanGrid/OU=DESY/CN=Wolfgang Ehrenfeld',
    '/O=GermanGrid/OU=LMU/CN=Cedric Serfon',
    '/O=GermanGrid/OU=LMU/CN=Gernot Krobath',
    '/O=GermanGrid/OU=LMU/CN=Johannes Ebke',
    '/O=GermanGrid/OU=LMU/CN=Johannes Elmsheuser',
    '/O=GermanGrid/OU=LMU/CN=Matthias Schott',
    '/O=GermanGrid/OU=MPPMU/CN=Emanuel Rauter',
    '/O=GermanGrid/OU=MPPMU/CN=Nabil Ghodbane',
    '/O=GermanGrid/OU=TUD/CN=Thomas Goepfert',
    '/O=GermanGrid/OU=UniBonn/CN=Duc Bao Ta',
    '/O=GermanGrid/OU=UniBonn/CN=Markus Warsinsky',
    '/O=GermanGrid/OU=UniBonn/CN=Peter Wienemann',
    '/O=GermanGrid/OU=UniBonn/CN=Robindra Prabhu',
    '/O=GermanGrid/OU=UniFreiburg/CN=Stan Lai',
    '/O=GermanGrid/OU=UniWuppertal/CN=Torsten Harenberg',
    '/O=Grid/O=NorduGrid/OU=fys.uio.no/CN=Alex Read',
    '/O=Grid/O=NorduGrid/OU=fys.uio.no/CN=Bjorn H. Samset',
    '/O=Grid/O=NorduGrid/OU=fys.uio.no/CN=Katarina Pajchel',
    '/O=Grid/O=NorduGrid/OU=nbi.dk/CN=Katrine Facius',
    '/O=Grid/O=NorduGrid/OU=nbi.dk/CN=Zofia Czyczula',
    '/O=dutchgrid/O=users/O=nikhef/CN=Gustavo Ordonez',
    '/O=dutchgrid/O=users/O=nikhef/CN=Martijn Gosselink',
    '/O=dutchgrid/O=users/O=nikhef/CN=Sander Klous',
    '/O=dutchgrid/O=users/O=nikhef/CN=Wouter Verkerke'
]